### ISSUE TITLE
Play Controls Not Working with I2S Sound board

### ISSUE THREAD

**Issue by colincoder** [rern/RuneUI_enhancement#39]
I recently added a PHat DAC board to my Pi3 that was previously working correctly with this addon.  Specifically the playback controls Previous, Stop, Play and Next buttons at the top worked.
After installing and activating the DAC from Pimoroni these buttons stop working.  All other operations worked correctly AFAICT. 
For more information [see this post](http://www.runeaudio.com/forum/pi-3b-runeaudio-v0-3beta-and-pimoroni-phat-dac-setup-t6407.html#p25331).
Thanks,
Colin

**Comment by rern** [comment]
Fixed.
